## [作業重點]
使用 Sklearn 中的 Lasso, Ridge 模型，來訓練各種資料集，務必了解送進去模型訓練的**資料型態**為何，也請了解模型中各項參數的意義。

機器學習的模型非常多種，但要訓練的資料多半有固定的格式，確保你了解訓練資料的格式為何，這樣在應用新模型時，就能夠最快的上手開始訓練！

## 練習時間
試著使用 sklearn datasets 的其他資料集 (boston, ...)，來訓練自己的線性迴歸模型，並加上適當的正則化來觀察訓練情形。

In [7]:
from sklearn import datasets, linear_model
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
boston = datasets.load_boston()

# OLS

In [4]:
X_train, X_test, y_train, y_test = train_test_split(boston.data,boston.target,test_size=0.2)

In [5]:
linear = linear_model.LinearRegression()
linear.fit(X_train,y_train)
y_pred = linear.predict(X_test)

In [6]:
print(linear.coef_)

[-7.99664097e-02  5.08063378e-02  7.58982315e-02  2.51292825e+00
 -1.63252671e+01  4.33166096e+00 -1.04729224e-02 -1.49298630e+00
  2.60391829e-01 -1.18970552e-02 -9.16721314e-01  1.00046277e-02
 -5.35076335e-01]


In [9]:
print(mean_squared_error(y_pred,y_test))

23.684188575470163


# Lasso

In [16]:
mse = []
coef = []
for i in np.arange(0.2,2,0.2):
    lasso = linear_model.Lasso(alpha=i)
    lasso.fit(X_train,y_train)
    y_pred = lasso.predict(X_test)
    mse.append(mean_squared_error(y_pred,y_test))
    coef.append(lasso.coef_)

In [18]:
mse

[24.609411257162375,
 24.106655854841392,
 24.013104779776157,
 24.211867486494842,
 24.74092723951493,
 25.6005538145705,
 26.790626692876778,
 27.021136370047188,
 27.209269103790508]

In [17]:
coef

[array([-0.06007733,  0.05211116,  0.00417171,  0.        , -0.        ,
         3.90977451, -0.01397386, -1.17886583,  0.22468144, -0.01374659,
        -0.75576997,  0.01068488, -0.60561506]),
 array([-0.05078053,  0.05233359,  0.        ,  0.        , -0.        ,
         3.24396777, -0.00480199, -1.06988865,  0.21938742, -0.0136145 ,
        -0.7515126 ,  0.01010955, -0.6518407 ]),
 array([-0.04172892,  0.05205286,  0.        ,  0.        , -0.        ,
         2.61092513,  0.        , -0.98536838,  0.21427825, -0.01350007,
        -0.74592025,  0.009593  , -0.69238758]),
 array([-0.03239903,  0.05215978,  0.        ,  0.        , -0.        ,
         1.95885207,  0.00755414, -0.88235185,  0.20982402, -0.01345607,
        -0.74145712,  0.00904379, -0.73683911]),
 array([-0.02305058,  0.0522779 ,  0.        ,  0.        , -0.        ,
         1.30629847,  0.01518355, -0.77884506,  0.20535314, -0.01341282,
        -0.73700816,  0.00849358, -0.78139942]),
 array([-0.01370186,  0.0

# Ridge

In [23]:
mse = []
coef = []
for i in np.arange(0.2,2,0.2):
    ridge = linear_model.Ridge(alpha=i)
    ridge.fit(X_train,y_train)
    y_pred = ridge.predict(X_test)
    mse.append(mean_squared_error(y_pred,y_test))
    coef.append(ridge.coef_)

In [24]:
mse

[23.815335276650295,
 23.931978260859644,
 24.032860591869337,
 24.119338330898827,
 24.193356563477685,
 24.25680595833951,
 24.31133990002174,
 24.358348464728245,
 24.398982915774205]

In [25]:
coef

[array([-7.75917633e-02,  5.09799081e-02,  6.59804759e-02,  2.50983592e+00,
        -1.40749542e+01,  4.35292384e+00, -1.26244086e-02, -1.46201261e+00,
         2.53693112e-01, -1.20315998e-02, -8.90705108e-01,  1.01346661e-02,
        -5.38122742e-01]),
 array([-7.58151397e-02,  5.11218798e-02,  5.84833302e-02,  2.50305464e+00,
        -1.23713201e+01,  4.36693926e+00, -1.42304414e-02, -1.43856922e+00,
         2.48714304e-01, -1.21377505e-02, -8.71167883e-01,  1.02319635e-02,
        -5.40588669e-01]),
 array([-7.44419143e-02,  5.12424408e-02,  5.26196537e-02,  2.49387227e+00,
        -1.10367134e+01,  4.37607243e+00, -1.54684591e-02, -1.42020835e+00,
         2.44895368e-01, -1.22246716e-02, -8.56002308e-01,  1.03071576e-02,
        -5.42661693e-01]),
 array([-0.07335356,  0.0513478 ,  0.04791005,  2.48307078, -9.96293407,
         4.38176385, -0.01644653, -1.4054392 ,  0.24189523, -0.01229795,
        -0.84392493,  0.01036673, -0.54445607]),
 array([-0.07247375,  0.05144195,  0.044